<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="contactinfo">
                <ul class="nav nav-pills">
                    <li><a href="#"><i class="fa fa-phone"></i>&nbsp;<?php echo $this->getData('phone'); ?></a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i>&nbsp;&nbsp;<?php echo $this->getData('email'); ?></a></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="social-icons pull-right">
                <ul class="nav navbar-nav">
                    <li><a href="<?php echo $this->getData('facebook'); ?>"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="<?php echo $this->getData('twitter'); ?>"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
