<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$helper         = $this->helper(\Magento\Search\Helper\Data::class);
$configProvider = $block->getData('configProvider');
?>
<div class="search_box pull-right">
    <form class="form minisearch" id="search_mini_form"
          action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <div class="control">
            <input id="search"
                <?php if ($configProvider->isSuggestionsAllowed()): ?>
                    data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->escapeUrl($helper->getSuggestUrl()) ?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                <?php endif; ?>
                   type="text"
                   name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                   value="<?= /* @noEscape */
                   $helper->getEscapedQueryText() ?>"
                   placeholder="<?= $block->escapeHtmlAttr(__('Search')) ?>"
                   class="input-text"
                   maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                   role="combobox"
                   aria-haspopup="false"
                   aria-autocomplete="both"
                   autocomplete="off"
                   aria-expanded="false"/>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <button type="submit" style="display: none;">
            <?= $block->getChildHtml() ?>
        </div>
    </form>
</div>
