<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="col-sm-3 col-sm-offset-1">
    <div class="single-widget">
        <h2>SUBSCRIBE SHOP</h2>
        <form class="searchform"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <input name="email" type="email" id="newsletter"
                   placeholder="<?= $block->escapeHtml(__('Your email address')) ?>"
                   data-mage-init='{"mage/trim-input":{}}'
                   data-validate="{required:true, 'validate-email':true}"
            />
            <button class="btn btn-default"
                    title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                    type="submit"
                    aria-label="Subscribe">
                <i class="fa fa-arrow-circle-o-right"></i>
            </button>
            <p>Get the most recent updates from <br>our site and be updated your self...</p>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }



</script>
